### ISSUE TITLE
Kill ReadGroupSets

### ISSUE THREAD

**Issue by adamnovak** [ga4gh/server#737] opened 2015-10-12 18:24 UTC
A ReadGroupSet is a very vague object with not really any particular associated semantics. We should replace it everywhere it is referenced with just the set of particular ReadGroup IDs being referred to.

**Comment by dcolligan** [comment] 2015-10-12 18:30
-1

A read group set = a BAM file

In any event, that's defined by the schema, so if this decision is made, it should be made there.

**Comment by jeromekelleher** [comment] 2015-10-12 18:37
Agree with @dcolligan --- this is a schema issue, so closing here.

**Closed by jeromekelleher** 2015-10-12 18:37 UTC

**Comment by diekhans** [comment] 2015-10-12 20:28
ReadGroupSet is the equivalent of most BAM files.  That is, a
set of read groups for a given sample library.  This is rather
important, as it is the unit that is normally analyzed.

I would suggest that the problem is not with ReadGroupSet
object, but how poorly specified it is.  It is marked for
improved specification in the documentation branch.

Just need someone who defined the object to step up.

**Comment by adamnovak** [comment] 2015-10-13 02:28
We probably should move the discussion over to a schemas issue, but I
figure I should explain in more than two words why I don't like
ReadGroupSets.

Basically, a ReadGroupSet *is* a BAM file, but the fact that two read
groups were in the same BAM file in and of itself doesn't really *mean*
anything, semantically. I can glom together any arbitrary combination of
ReadGroups from different samples, sequencers, and aligners into a single
BAM file. The BAM spec supports it just fine.

You might complain that that would be a bad idea, and that putting two read
groups from different samples/sequencers/pipelines into the same BAM is
going to confuse people, because they might assume that they actually did
belong to one sample/sequencer technology/alignment pipeline. But if it's
these pieces of metadata that are important, then that metadata is what we
should use to organize our ReadGroups. Having a ReadGroupSet that exists to
represent a BAM file is only a good idea if we can enforce that being in
the same BAM file actually means something consistent across data sets, and
that the API endpoint you happen to be hitting against today hasn't grouped
all of its reads into BAM files by first letter or some other useless
convention.

If the point of ReadGroupSet is to represent particular application- or
data-source-specific sets of ReadGroups (i.e. document the arrangement into
BAM files upon import form some other repository, where being in a BAM file
means something repository-specific), we would probably want a
lighter-weight, less-fundamental-to-the-whole-API representation, where a
ReadGroupSet is just an assertion that this other study grouped together
these ReadGroups under this external identifier, with other-study-specific
semantics.
