### ISSUE TITLE
Id refactor

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#367] opened 2015-04-22 18:02 UTC
@macieksmuga and I were discussing this.

There is a question of how Ids should be generated for objects inside the reference server.  So far we seem to be doing a concatenation of filenames / existing ids to produce a new unique id.  Another solution would be UUIDs.  A third would be using ids assigned by a third-party system, like a SQL database we use to store objects (in the graph).

Proposal: we should have a option in the server config to choose the id strategy we use at startup.  The code should be refactored to read this option and assign Ids based on the strategy chosen.

The advantage of this would be 1) more flexibility for the user 2) an easy way to compare which Id generation strategies would work best 3) whenever the Id generation method argument is definitively settled, the change on our end will be as simple as setting that to be the default serverconfig option.

**Comment by dcolligan** [comment] 2015-04-22 18:05
FYI python has a `uuid` module https://docs.python.org/2/library/uuid.html

**Comment by diekhans** [comment] 2015-04-22 19:03
I strongly advocate for UUIDs only.  We want to push GA4GH to go
to a GUID system, where GUIDs are either digests computed
directly from the data or UUID where digests will not work well.

There is still a need to link to external database through
secondary identifiers, however it opens up a lot of complexity
to no control the primary identifier space.

It's strategic for GA4GH to address the data identification
issue.  This is a huge problem for bioinformatics and genomics.
We need to demonstrate this in the server.

Since ids are wide spread through the server, It will also
simplify testing.

+1 UUIDs, -2^31 anything else

**Comment by jeromekelleher** [comment] 2015-04-23 13:43
UUIDs are great, but we need IDs to be stable across server restarts. We also need to be able to find a given object when we have its ID. So, when we need to support `GET /variants/{id}` we can know how to find it by decomposing the ID string. This is a strong requirement for me. 

IDs here are *internal* to the implementation, and there is no requirement about their structure in the spec. Clients should *not* use the object IDs as anything other than an opaque identifier. I don't see a lot of point in giving admins choice in the ID selection strategy --- they're for the server's use, not anyone else's.

**Comment by diekhans** [comment] 2015-04-23 14:07
Yes, UUID should be used when stable external ids are required,
but something truly internal is up to the pleasure of the
developers.

I thought that external was the point.  Otherwise, why would
someone configuring the server care?

**Comment by jeromekelleher** [comment] 2015-04-23 14:20
My understanding of the object ID fields is that they are internal IDs only, and are never intended to be used as a way of comparing objects across instances. Stable UUIDs for objects across repositories are a separate (and hugely important!) issue.

**Comment by diekhans** [comment] 2015-04-23 14:42
The id fields in the object are exposed to the user between ReST
requests and thus stable in some sense.  The scope of stable is
a big, unresolved issue within the DWG.  Right now, it's
undefined.

We (UCSC people I brainwash) feel that it's vital that ids be
stable be global for all conforming GA4GH servers.  This enables
a world of functional, such as reproducible, caching and
encouraging data sharing by making citation easy.

**Comment by jeromekelleher** [comment] 2015-04-23 15:11
Sure, the IDs must be stable on a given server, that seems clear. UUIDs for every read and variant though? That's a very strong requirement, and would need a huge lookup table for us to support it. We want to remain stateless and work directly from VCF and BAM. Requiring a UUID for each read and variant would make this impossible I think.

UUID for References, ReadGroups, VariantSets, etc, I totally agree with.

**Comment by diekhans** [comment] 2015-04-23 16:37
Agreed UUIDs should be on the immutable units, e.g. ReadGroups.

Ids within an immutable unit could be simple integers, however I think
they still should be globally stable withing the readgroup and all queries
need to be scoped with the immutable unit id.

Thus a read query would be (ReadGroupUUID readNumber).

I am really glad this is coming up.

**Comment by jeromekelleher** [comment] 2015-04-23 16:44
OK, that seems reasonable. So, is the idea is ``variantSetId`` is a UUID and is the same across different servers, and the variantId is then ``"{}:{}".format(variantSetId, variantNumber)``? We need to make sure that we can efficiently retrieve the individual variants/reads, but I think something like this is workable.

So how do we define a UUID for a variant set? Isn't this something that a working group has been working on?

**Comment by diekhans** [comment] 2015-04-23 16:52
That is the idea, although I suspect for efficiency reasons we
will eventually have to support multiple variants, reads, etc,
per query.  But that could be restricted to a single UUID.

The containers and work flows group has been discussing data
digests as a way of generating GUIDs.  I am not sure were that
is at.  It kind of doesn't belong there, but because Matt is
interested in digests, it's being discussed there.

For anything that is large enough to generate a GUID from a data
digest, that should be the approach.

The UCSC BD2K center, which includes Berkeley, has put in a
request for a supplement to cover digests and identification.

**Comment by macieksmuga** [comment] 2015-04-23 18:11
Thanks @diekhans and @jeromekelleher for the debate! 
This is a critical issue to me right now, as I'm putting the finishing touches on the SQL schemas for reference/variation graphs, and I'd like to settle on the right way to do this. Sounds like I should switch to UUID's for persistent entities like ReferenceSets, and then have a compound (colon-separated works for me) ID for each Reference, with a simple integer identifier for the second part of this ID (mapping nicely to the numeric ID column as currently defined in the Reference table).

**Comment by macieksmuga** [comment] 2015-04-23 18:14
Whoops, reading more carefully: UUID for each reference sequence too. There will be an awful lot of these in the graph world...
Also, would callSets warrant a UUID as well?

**Comment by diekhans** [comment] 2015-04-23 18:17
The way to think about it is: what is the immutable unit.

Also, a UUID is only 128 bits in binary.

How many and how big.

CallSet for sure need a UUID.

Alleles too, since we want ti link to them from different
variants.

**Comment by dcolligan** [comment] 2015-05-13 18:12
Can I close this issue?  It seems like something that some working group will get back to us in the future on, and not really actionable right now...

**Comment by macieksmuga** [comment] 2015-05-13 23:20
I agree with @dcolligan - there are bigger fish to fry right now - but let's keep the above discussion in mind the next time we cycle around to this issue...

**Comment by jeromekelleher** [comment] 2015-05-14 15:37
Yes, lets close this for now.

**Closed by jeromekelleher** 2015-05-14 15:37 UTC
