### ISSUE TITLE
Modify requirement of one reference contig per FASTA file

### ISSUE THREAD

**Issue by macieksmuga** [ga4gh/server#829] opened 2016-01-07 16:53 UTC
Per discussion in #814, @diekhans noted that some more complicated references (alt loci and the like) may contain multiple contigs per FASTA file. Also, I believe the entire GRCh38 reference is optionally packaged in a single FASTA:
```
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA_000001405.20_GRCh38.p5/GCA_000001405.20_GRCh38.p5_genomic.fa.gz
```
which would make installing it trivially easy on a reference server instance.

Note that each reference contig within the file exists as a separate FASTA record, thus it should be easy to parse these out into separate entities within the server.

**Comment by jeromekelleher** [comment] 2016-03-24 16:32
Closing this as a duplicate of #955.

**Closed by jeromekelleher** 2016-03-24 16:32 UTC
