### ISSUE TITLE
/references/search ignores (bogus) accession parameter?

### ISSUE THREAD

**Issue by hjellinek** [ga4gh/server#781] opened 2015-11-12 19:34 UTC
I'm running the compliance test `ReferencesSearchIT.checkSearchingReferencesWithInvalidAccessionReturnsEmpty` against the compliance data from the master branch of ga4gh/compliance loaded into the latest ga4gh/server.

The test creates a `SearchReferencesRequest` that contains the ID of reference set `hg37` (`"aGczNw=="`) and a randomly-generated accession ID (`"14e6b2b6-b1b8-440b-b599-6e58b4a70ed8"`) that, of course, shouldn't match any real reference.  The request looks like this:

```json
{"referenceSetId": "aGczNw==",
 "md5checksums": [],
 "accessions": ["14e6b2b6-b1b8-440b-b599-6e58b4a70ed8"],
 "pageSize": null, "pageToken": null}
```

The expected response is a `SearchReferencesResponse` with the field `references` containing the empty list, something like this:

```json
{"references": [],
 "nextPageToken": null}
```

However, the actual response is:

```json
{"references": [{"id": "aGczNzpyZWZfYnJjYTE=", "length": 81188, "md5checksum": "90977a37195d3fd247e4916b5b4cbae8", "name": "ref_brca1", "sourceURI": "https://github.com/ga4gh/compliance/blob/master/test-data/ref_brca1.fa", "sourceAccessions": ["GA4GH_CTS_01_BRCA1"], "isDerived": true, "sourceDivergence": null, "ncbiTaxonId": 9606}],
 "nextPageToken": null}
```
It appears that the server ignores bogus accession values; it's possible that it ignores the `accessions` parameter entirely.

**Comment by jeromekelleher** [comment] 2015-11-12 20:01
Thanks @hjellinek , good spot.

**Comment by dcolligan** [comment] 2015-11-16 12:59
Can't reproduce ... what version of the code are you using?  The `SearchReferencesRequest` object has an `accession` scalar, not an `accessions` array.  The `accession` parameter is not ignored in `backend.py`.
```
$ python client_dev.py -vv references-search --referenceSetId R1JDaDM4LXN1YnNldA== --accession does-not-exist  http://localhost:8000
DEBUG:ga4gh.client:request:{"pageToken": null, "pageSize": null, "referenceSetId": "R1JDaDM4LXN1YnNldA==", "accession": "does-not-exist", "md5checksum": null}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:requests.packages.urllib3.connectionpool:"POST /references/search?key=invalid HTTP/1.1" 200 40
DEBUG:ga4gh.client:response:{"nextPageToken": null,"references": []}
```

**Comment by jeromekelleher** [comment] 2015-11-16 18:00
I think I see what's happened here --- we've turned off input validation so that the bad JSON provided wasn't flagged. Ignoring the  provided ``accessions`` value is the correct behaviour. Closing; thanks for following up @dcolligan.

**Closed by jeromekelleher** 2015-11-16 18:00 UTC
Labels: bug
