### ISSUE TITLE
Need a checklist describing what is current working in the server

### ISSUE THREAD

**Issue by diekhans** [ga4gh/server#430] opened 2015-06-01 17:43 UTC
It's difficult to understand exactly what is implemented in the server.  What protocols, what schemas, fields in the schema, and methods.  A maintained checklist style document in the tree would be most helpful

**Comment by dcolligan** [comment] 2015-06-01 18:50
This seems like a lot of work for not very much benefit.  The issue tracker captures a lot of this information already and there are places in the code that could tell one something about the server's functionality... `frontend.py` identifies that URL paths that are implemented, for instance.  There are also a lot of fields that change frequently, some of which are not implemented but half implemented, etc. etc.  Maybe you could tell us what use for this you had in mind?

**Comment by wstidolph** [comment] 2015-06-01 18:54
Well, one use is to prioritize subtasks of building a conformance test :) and reduce exploratory time lost to "maybe I did this wrong" exploration/time-loss for someone making a client app.

**Comment by diekhans** [comment] 2015-06-01 18:59
I hope it's not a lot of work, it's just a checklist.  It
appears that many request are not done and there is no way to
get this except try it and get back a 501.

This is for people trying to use the server, not develop it.

No one knows what is implemented and what is not.  They just
have to try it.  There appear to be unimplemented requests and
fields that there is no way to get into the server (and some
probably because they make no sense).

It's kind of like release notes.

**Comment by wstidolph** [comment] 2015-06-01 19:02
IMO, the checklist info should be fetchable as a JSON doc from the live server, so a client can use it to adapt to the realities on the ground. For example, a CTK might skip (and fail) a bunch of tests if a required message wasn't implemented, or if the server's schema version wasn't the same as what the tests assumed.

**Comment by diekhans** [comment] 2015-06-01 19:10
I don't really want to add more to the API to find out what is
implement, I just want to implement it.

Failing the tests is the right thing to do!!  Fail loud


Being able to discover the schema version the server implements
seems essential.

**Comment by pgrosu** [comment] 2015-06-01 19:14
Having a checklist is essential to keep on track - I create one for all my projects.  I even recommended something along the same lines about a [couple of months ago](https://github.com/ga4gh/server/issues/305#issuecomment-87960556) with a recommendation to @ekg's [variant graphs tools project](https://github.com/ekg/vg/) as an example to draw inspiration from, specifically his Development section. This does not have to be fancy, and can even be a Github [formatted table](https://help.github.com/articles/github-flavored-markdown/#tables) that would be periodically updated.

**Comment by pgrosu** [comment] 2015-06-01 19:18
I agree with @diekhans as we are a TDD (test-driven development) implementation and that is what is driving our incremental implementations, and keeping in sync with what the API is telling us we should be.

**Comment by dcolligan** [comment] 2015-06-01 19:19
All of the paths that are active are listed on a web page upon server startup... just request GET /

**Comment by dcolligan** [comment] 2015-06-01 19:22
@diekhans how is the checklist going to be any different from a less information rich version of the issue tracker?  If something is unimplemented that we want, an issue should be filed.  If more information about server operation is needed, that can go into the documentation.

**Comment by pgrosu** [comment] 2015-06-01 19:23
@dcolligan  But they need to be publicly documented as well.  Not everyone will download the code, run the server to check these things out.  By documenting it on a website it will keep everyone in sync with the project.

**Comment by wstidolph** [comment] 2015-06-01 19:27
The test suite's reason for having this sort of thing be machine-friendly
live-in-the-server is that since these are inter-system tests, the test
will fail *slowly* and an incomplete implementation in a function will
block all the corner-case tests which involve that function. Yes, those are
real failures and we will announce that loudly - but if we have a lot of
tests (and we should) then a known-incomplete condition of the server under
test will cause a bunch of essentially the same error reports, and people
become less willing to use the test suite (since it's full of repetition,
and it runs slow). The tests become *less* useful in driving development
when there's multiple reports driven by the same fault.

If we can tag/Categorize the tests and skip-fail the ones that are disabled
using some notification from the server then we can announce the same test
results more quickly, and not have to evaluate every failure as "oh, that's
another symptom of misordering of the X and Y fields"


On Mon, Jun 1, 2015 at 12:22 PM, Danny Colligan <notifications@github.com>
wrote:

> @diekhans <https://github.com/diekhans> how is the checklist going to be
> any different from a less information rich version of the issue tracker? If
> something is unimplemented that we want, an issue should be filed. If more
> information about server operation is needed, that can go into the
> documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ga4gh/server/issues/430#issuecomment-107677050>.
>



-- 
  Wayne Stidolph  | (831) 419 7146 | LinkedIn
<http://www.linkedin.com/in/waynestidolph> | Google+
<https://google.com/+WayneStidolph> | twitter
<https://twitter.com/#!/wstidolph> | personal blog
<http://waynedge.blogspot.com/>

**Comment by diekhans** [comment] 2015-06-01 19:39
How can one go to the issue tracker and quickly find out what has
been implemented in any particular release or commit level?  This
seems very time consuming

The suggestion is this should be part of the end user
documentation.  People not developing the server have no idea
what actually works.  It doesn't implement the full 0.5.1 API
and doesn't implement all of the attributes.

If there is already in the doc and we have missed it, then
we need to make it more obvious.

Ask a question: how does an end user find out what has been
implemented?

**Comment by pgrosu** [comment] 2015-06-01 19:40
I agree with a test suite, but that would be separate from the documentation.  Regarding skipping tests, usually the associated test configuration file would be sufficient to select what tests should be included and which should be excluded.  It probably is not a good idea to skip tests, since some tests depend on the type of testing that would be performed (i.e. unit, integration, regression, etc.)

**Comment by diekhans** [comment] 2015-06-01 19:42
how is this different than a 501?

I can see how it is useful, but I am not sure it's very high
priority.

**Comment by wstidolph** [comment] 2015-06-01 19:56
As to how it's different than a 501 - an unexpected 5xx certainly says
"server error" but that doesn't tell the CTK what is wrong, what tests
might be skippable as a result. So absent some form of tagging and
advice-from-the-server, the CTK will go on to run the next test, and
generate the next failure, and the next block of log entries.

But I agree there's a risk of inappropriate test-skipping , and that a
human can scrounge that information from whatever sources and build the
test-config file they want, and that "YAGNI" suggests to not worry about it
until people complain about the test failure volume.

I look forward to the collected-capabilities checklist! (I need it for the
CTK already)

On Mon, Jun 1, 2015 at 12:43 PM, Mark Diekhans <notifications@github.com>
wrote:

>
> how is this different than a 501?
>
> I can see how it is useful, but I am not sure it's very high
> priority.
>
> Wayne Stidolph <notifications@github.com> writes:
> > The test suite's reason for having this sort of thing be machine-friendly
> > live-in-the-server is that since these are inter-system tests, the test
> > will fail *slowly* and an incomplete implementation in a function will
> > block all the corner-case tests which involve that function. Yes, those
> are
> > real failures and we will announce that loudly - but if we have a lot of
> > tests (and we should) then a known-incomplete condition of the server
> under
> > test will cause a bunch of essentially the same error reports, and people
> > become less willing to use the test suite (since it's full of repetition,
> > and it runs slow). The tests become *less* useful in driving development
> > when there's multiple reports driven by the same fault.
> >
> > If we can tag/Categorize the tests and skip-fail the ones that are
> disabled
> > using some notification from the server then we can announce the same
> test
> > results more quickly, and not have to evaluate every failure as "oh,
> that's
> > another symptom of misordering of the X and Y fields"
> >
> >
> > On Mon, Jun 1, 2015 at 12:22 PM, Danny Colligan <
> notifications@github.com>
> > wrote:
> >
> > > @diekhans <https://github.com/diekhans> how is the checklist going to
> be
> > > any different from a less information rich version of the issue
> tracker? If
> > > something is unimplemented that we want, an issue should be filed. If
> more
> > > information about server operation is needed, that can go into the
> > > documentation.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ga4gh/server/issues/430#issuecomment-107677050>.
> > >
> >
> >
> >
> > --
> > Wayne Stidolph | (831) 419 7146 | LinkedIn
> > <http://www.linkedin.com/in/waynestidolph> | Google+
> > <https://google.com/+WayneStidolph> | twitter
> > <https://twitter.com/#!/wstidolph> | personal blog
> > <http://waynedge.blogspot.com/>
> >
> > —
> > Reply to this email directly or view it on GitHub.*
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ga4gh/server/issues/430#issuecomment-107681485>.
>



-- 
  Wayne Stidolph  | (831) 419 7146 | LinkedIn
<http://www.linkedin.com/in/waynestidolph> | Google+
<https://google.com/+WayneStidolph> | twitter
<https://twitter.com/#!/wstidolph> | personal blog
<http://waynedge.blogspot.com/>

**Comment by dcolligan** [comment] 2015-06-01 20:13
We do have some release notes, but these are very sparse:

https://github.com/ga4gh/server/releases

**Comment by dcolligan** [comment] 2015-06-01 20:17
@diekhans ok, how does another top-level item on our docs site called "Current Implementation Status" (or whatever) sound?

http://ga4gh-reference-implementation.readthedocs.org/en/develop/

Also I'd like to hear what @jeromekelleher thinks.

**Comment by wstidolph** [comment] 2015-06-01 20:20
Would that doc be versioned along with the Server? So if I check out a
given Server tag/whatever, I get the correct "Current Implementation
Status"?

On Mon, Jun 1, 2015 at 1:17 PM, Danny Colligan <notifications@github.com>
wrote:

> @diekhans <https://github.com/diekhans> ok, how does another top-level
> item on our docs site called "Current Implementation Status" (or whatever)
> sound?
>
> http://ga4gh-reference-implementation.readthedocs.org/en/develop/
>
> Also I'd like to hear what @jeromekelleher
> <https://github.com/jeromekelleher> thinks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ga4gh/server/issues/430#issuecomment-107694574>.
>



-- 
  Wayne Stidolph  | (831) 419 7146 | LinkedIn
<http://www.linkedin.com/in/waynestidolph> | Google+
<https://google.com/+WayneStidolph> | twitter
<https://twitter.com/#!/wstidolph> | personal blog
<http://waynedge.blogspot.com/>

**Comment by dcolligan** [comment] 2015-06-01 20:21
Yes, the documentation is versioned along with the server.  See the `docs` directory.

**Comment by diekhans** [comment] 2015-06-01 20:22
501 == not implemented ;-)

but at this point, I would be happy to have
something resembling a coherent API and servers
that produce gigabytes of failure message.

Skipped tests should still be failures, but right now any kind
of optimization is low priority.

**Comment by diekhans** [comment] 2015-06-01 20:24
Perfect!

**Comment by jeromekelleher** [comment] 2015-06-02 11:40
Sorry to come in late to this discussion. There are a couple of points here:

1. End points that are in the schema that we haven't implemented should return 501. We currently return 404, and this is a bug. We should fix this in master, and backport the changes to the released version.
2. I don't think we should implement anything that isn't in the schema, other than the information page at '/'. Our API versioning system (which is *not* part of the protocol) with URL prefixes is working out to be troublesome, and apparently not particularly helpful to users. The official API documentation needs to be updated with specific instructions on how API versioning should be handled, preferably via HTTP the Content-Type.
3. I think we should add an implementation status page to the documentation as @dcolligan has suggested above. We should add this to the documentation for our bugfix release, so that it's clear what this supports and doesn't. Possible things to note:
   - Limited dataset support: `datasetId` fields are currently ignored, etc.
   - Good support for variants API, should be production ready.
   - Initial support for Reads API. Works, but needs expert review to ensure BAM->API conversion is done    correctly.
   - References not supported

**Comment by dcolligan** [comment] 2015-06-02 11:54
Cool, I've filed some more specific issues based off of this thread.  Unless anyone objects, I think this thread should be closed and discussion should take place (if needed) in the more specific threads and (if needed) other bugs should be filed for other specific issues.

**Comment by jeromekelleher** [comment] 2015-06-02 11:55
Agreed; closing.

**Closed by jeromekelleher** 2015-06-02 11:55 UTC
