### ISSUE TITLE
Import/export data using command line API rather than copying files

### ISSUE THREAD

**Issue by diekhans** [ga4gh/server#573] opened 2015-08-13 19:37 UTC
As the API evolves, it will become harder to robustly add data to the reference server  by manually installing files.  Suggest developing a command line API to install and remove data from a reference server.  Advantages include:

- Simplify and insure accurate install of standard file formats
- Isolate internal structure of files from user.
- Provide way to add additional metedata required by the API but not part of standard file format
- Allow for data validation before server is started
- Build required indexes, either standard ones, such as BAM indexes, or reference-server specific ones, such as identifier indexes
- Simplify automation of reference server setup for production sites

**Comment by jeromekelleher** [comment] 2015-08-14 07:44
Good ideas...

**Comment by kozbo** [comment] 2016-03-16 01:23
Looks like a duplicate of #814. @dcolligan should we close this too?

**Comment by dcolligan** [comment] 2016-03-16 14:46
Yeah, this is the repo manager

**Closed by dcolligan** 2016-03-16 14:46 UTC
