### ISSUE TITLE
Variant parsing (bugs?)

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1220] opened 2016-05-06 23:29 UTC
It appears some of the variants are receiving empty alternateBases in the 1kg vcf.

```
{"info":{"EUR_AF":["0.0010000000475","0.0010000000475"],"SAS_AF":["0.00820000004023","0.0"],"AC":["9","1"],"END":["50855"],"AF":["0.00179711997043","0.000199681002414"],"AFR_AF":["0.0","0.0"],"AMR_AF":["0.0","0.0"],"AN":["5008"],"SVTYPE":["CNV"],"VT":["SV"],"EAS_AF":["0.0","0.0"],"CS":["DUP_gs"],"NS":["2504"],"DP":["19385"]},"updated":null,"end":50855,"calls":[],"created":null,"variantSetId":"WyIxa2dlbm9tZXMiLCJ2cyIsInJlbGVhc2UiXQ","referenceBases":"G","start":22112,"names":["esv3603715","esv3603716"],"alternateBases":["",""],"referenceName":"5","id":"WyIxa2dlbm9tZXMiLCJ2cyIsInJlbGVhc2UiLCI1IiwiMjIxMTIiLCJiZmNjYzI2NmRjZmQ4NjFlYjNkZGM3NTJiNzBhYTI0YSJd"}
```

Here is another variant where it appears the INFO.AA field has been parsed incorrectly.

```
{"info":{"EUR_AF":["0.0"],"SAS_AF":["0.0"],"AC":["1"],"AA":["N|||"],"AF":["0.000199681002414"],"AFR_AF":["0.00079999997979"],"AMR_AF":["0.0"],"AN":["5008"],"VT":["SNP"],"EAS_AF":["0.0"],"NS":["2504"],"DP":["14055"]},"updated":null,"end":47248,"calls":[],"created":null,"variantSetId":"WyIxa2dlbm9tZXMiLCJ2cyIsInJlbGVhc2UiXQ","referenceBases":"G","start":47247,"names":["rs377370869"],"alternateBases":["A"],"referenceName":"5","id":"WyIxa2dlbm9tZXMiLCJ2cyIsInJlbGVhc2UiLCI1IiwiNDcyNDciLCJmMzQxM2JkMTVjNWNiYzI4ZDFiYjY2OGY4ZWM2NzczMiJd"}
```

**Comment by bioinformed** [comment] 2016-05-07 00:19
Please let me know if this turns out to be a pysam VCF parsing bug.

**Comment by jeromekelleher** [comment] 2016-05-09 08:46
Nicely spotted @david4096, great work. We'll need the original VCF entries to make progress on this. Can you paste in the (relevant bits of) the VCF lines? Creating a minimal VCF file for each consisting of just the header and the VCF line in question will be useful for further debugging too.

**Comment by Kusdhill** [comment] 2016-05-11 23:34
https://github.com/david4096/bioapi-examples/blob/master/variantParsingBug.ipynb

After looking at the pysam output, alternate alleles were found. It seems that the problem is taking place somewhere other than in pysam.

**Comment by jeromekelleher** [comment] 2016-05-12 20:52
The original VCF text would still be informative --- would it be possible to get it here for reference?

**Comment by david4096** [comment] 2016-05-12 21:03
I've been having trouble replicating the result of the [first variant](http://1kgenomes.ga4gh.org/variants/WyIxa2dlbm9tZXMiLCJ2cyIsInJlbGVhc2UiLCI1IiwiMjIxMTIiLCJiZmNjYzI2NmRjZmQ4NjFlYjNkZGM3NTJiNzBhYTI0YSJd) with empty `alternateBases`, `<CN0>` and `<CN2>` are now returned properly.  

The [second case](http://1kgenomes.ga4gh.org/variants/WyIxa2dlbm9tZXMiLCJ2cyIsInJlbGVhc2UiLCI1IiwiNDcyNDciLCJmMzQxM2JkMTVjNWNiYzI4ZDFiYjY2OGY4ZWM2NzczMiJd), where there are `|` in the AA field, appears to be in the underlying data.

```
INFO.AA	Ancestral Allele. Format: AA|REF|ALT|IndelType. AA: Ancestral allele, REF:Reference Allele, ALT:Alternate Allele, IndelType:Type of Indel (REF, ALT and IndelType are only defined for indels)	
```

This field is multiply valued but does not follow comma separation. I'm happy to close this if the data appears as expected! I don't think pysam is expected to expand structures within each info item.

https://github.com/david4096/bioapi-examples/blob/master/python_notebooks/variantParsingBug.ipynb

**Comment by bioinformed** [comment] 2016-05-12 21:49
Correct.  Those internal '|' delimiters are not part of the VCF spec and are an application-specific encoding convention.  pysam/htslib don't know anything about those semantics, so it is up to the application to apply the additional parsing logic.

**Comment by jeromekelleher** [comment] 2016-05-13 07:49
I think we're doing everything we can here --- we can only return what's in the underlying VCF. Please close the issue if you're happy with this @david4096.

**Comment by jeromekelleher** [comment] 2016-05-17 13:26
Can we close this issue @david4096?

**Closed** 2016-05-17 18:30 UTC
