### ISSUE TITLE
this query get wrong server response back.

### ISSUE THREAD

**Issue by jingchunzhu** [ga4gh/server#433] opened 2015-06-02 21:17 UTC
This following query against umd get 2520 variants back, many are not within the start and end interval
python client_dev.py -vv variants-search --variantSetIds umd --referenceName 17 --start 41227747  --end 41244748 --pageSize 1000 http://ec2-54-148-207-224.us-west-2.compute.amazonaws.com:8000/v0.6.e6d6074
2520 variants

The most strange thing is that the xena browser client (in javascript) also get the "same"(same in the sense that the same number of variants returned) wrong answer back.

however,  curl command seems to get the correct response back.

curl --data '{ "callSetIds": [],  "end": 41244748, "referenceName": "17",  "start":41227747,  "variantSetIds": ["umd”], “pageSize”:1000}’ --header 'Content-Type: application/json' http://ec2-54-148-207-224.us-west-2.compute.amazonaws.com:8000/v0.6.e6d6074/variants/search

**Comment by jingchunzhu** [comment] 2015-06-02 22:36
All three clients are now consistently getting the incorrect response back. 


pageSize parameter in the  curl command does not  seem to be used. once you manually add pageToken parameter, it also triggers the incorrect response back from the server. 

curl --data '{ "callSetIds": [], "end": 41244748, "referenceName": "17", "start":41227747, "variantSetIds": ["umd”], “pageSize”:1000}’ --header 'Content-Type: application/json' http://ec2-54-148-207-224.us-west-2.compute.amazonaws.com:8000/v0.6.e6d6074/variants/search

**Comment by dcolligan** [comment] 2015-06-02 22:50
Which version of the server is this?  Is it an old one that has the bug we fixed in this update?  https://github.com/ga4gh/server/releases/tag/v0.1.1

It looks like you are running 0.1.0b1, not 0.1.1.  Try updating and see what happens.

**Comment by jingchunzhu** [comment] 2015-06-04 17:43
For querying umd database on chr17 between position 41227747 to 41244748 the server found 2520 variants, many are not in this interval.  

here are just a random copy of paste a few that are outside (both start and end) the interval. 

variant_start     variant_end
41226453        41226454
41226456        41226457
41226473        41226474
41226487        41226488
41226487        41226488
41226487        41226488
41226487        41226488
41226487        41226488
41226487        41226488

You should see the same thing using the python client.


server implementation used:  http://ec2-54-148-207-224.us-west-2.compute.amazonaws.com:8000/v0.5.1  

GA4GH reference server 0.1.1

Protocol version 0.5.1

Operations available

Method	Path
GET	/v0.5.1
POST	/v0.5.1/callsets/search
POST	/v0.5.1/readgroupsets/search
POST	/v0.5.1/reads/search
POST	/v0.5.1/referencesets/search
POST	/v0.5.1/variants/search
POST	/v0.5.1/variantsets/search
Uptime

Running since 13 hours ago (04:23:35 04 Jun 2015)
Configuration

Key	Value
DEBUG	True
REQUEST_VALIDATION	False
RESPONSE_VALIDATION	False
Data

VariantSets

Clinvar
ex_lovd
lovd
1000_genomes
exac
bic
umd
ReadGroupSets

**Comment by dcolligan** [comment] 2015-06-04 19:06
@jeromekelleher do you have any guesses why this might be happening?  it seems like backend.py should iterate past these variants that are getting returned, since they're outside the requested range...

**Comment by jeromekelleher** [comment] 2015-06-08 09:16
Yes, it looks like this is a bug in our paging code. Thanks for reporting this @jingchunzhu.

@dcolligan, I've no guesses right now. We'll need to get the data and try to reproduce this locally so we can get to the bottom of it. @jingchunzhu, can you provide us with some information on how we can download this dataset so we can debug the problem please?

**Comment by jingchunzhu** [comment] 2015-06-08 20:44
Jerome;

use data on GA4GH server at :
http://ec2-54-148-207-224.us-west-2.compute.amazonaws.com:7000/v0.6.e6d6074

python command line : python client_dev.py -vv variants-search
--variantSetIds umd --referenceName 17 --start 41227747 --end 41244748
--pageSize 1000
http://ec2-54-148-207-224.us-west-2.compute.amazonaws.com:7000/v0.6.e6d6074

jing

**Comment by dcolligan** [comment] 2015-06-09 13:25
@jingchunzhu , it would be better if we actually had access to the data that this server is using, both because we could cross-reference the returned results with the actual data and set breakpoints on our locally running server.

**Comment by jeromekelleher** [comment] 2015-06-09 14:04
Yes, we really do need to get the data to reproduce this, sorry @jingchunzhu. Is there a download link that we can use to get at it?

**Comment by jingchunzhu** [comment] 2015-06-09 18:55
Charlie,   can we share the umd BRCA vcf files with Jerome for figuring out
the server bug?

Jing

**Comment by jingchunzhu** [comment] 2015-06-09 18:59
Yes, I believe so. Do you want to know where it's located on the server? Or
do you want me to send the file to him directly?

-Charlie

**Comment by jingchunzhu** [comment] 2015-06-09 19:12
Jerome,

Attached is the data file (in vcf).

jing

**Comment by jeromekelleher** [comment] 2015-06-09 20:31
I'm afraid attachments don't work for github --- you can either post a download link here or send the file to me over email at jk@well.ox.ac.uk. Thanks.

**Comment by pgrosu** [comment] 2015-06-09 23:35
@jingchunzhu, @jeromekelleher  You can attach files into comments on GitHub if you rename your file to with a `.png` extension and just drag-and-drop it into the comment section.  Then anyone can download/save the PNG file and rename it back to the original extension and see the complete contents.

**Comment by dcolligan** [comment] 2015-06-10 13:38
@jingchunzhu can you also email me the index file you are using for that vcf file?

**Comment by jingchunzhu** [comment] 2015-06-10 14:23
Charlie,

Can you help?

Jing

**Comment by jingchunzhu** [comment] 2015-06-10 19:11
Here's the index file. Is there anything else you guys need?

-Charlie

**Comment by dcolligan** [comment] 2015-06-10 19:55
I didn't receive it.  You'll need to mail it to me as an attachment.

**Comment by jeromekelleher** [comment] 2015-06-11 05:15
I think you can remake the index using tabix @dcolligan, it shouldn't be necessary to get the original index (unless we're having trouble reproducing the problem).

**Comment by dcolligan** [comment] 2015-06-15 21:11
For this particular query, it looks like 529 out of 2520 variants returned to the client are defective, all because the start and end of the returned variant are less than the request's start attribute.  It looks like a problem with the paging code, as 1991 variants are returned by the lower-level query to `HtslibVariantSet.getVariants` (and none of those have start and end less than `startPosition`).  Continuing to investigate...

**Comment by dcolligan** [comment] 2015-06-15 22:07
@jeromekelleher it looks like our algorithm only works if the VCF is ordered, and this VCF appears to be unordered (as in, when we pull in the variants they are unordered by (variant.start, variant.end))... I think that's the problem

**Comment by diekhans** [comment] 2015-06-15 23:12
Suggest requiring VCF to be ordered.  Ranges searches are going to be slower
if not ordered.

**Comment by bioinformed** [comment] 2015-06-16 00:16
VCF and BCF files are required by the specification to be position
ordered.  We would be well within our rights to enforce that requirement
and fail loudly.

2. POS - position: The reference position, with the 1st base having
position 1. *Positions are sorted numerically, in increasing order, within
each reference sequence CHROM*. It is permitted to have multiple records
with the same POS. Telomeres are indicated by using positions 0 or N+1,
where N is the length of the corresponding chromosome or contig. (Integer,
Required)

**Comment by lh3** [comment] 2015-06-16 01:31
Isn't the server using htslib? Bcftools/tabix should refuse to create the index if the input is not sorted. If it is not reporting the error, there is a bug.

**Comment by dcolligan** [comment] 2015-06-16 02:06
Ok, the variants we get out of the VCF file are ordered by (variant.start) within the reference, just not (variant.start, variant.end).  This is both conforming to the specification and doesn't, so far as I can tell, present a problem for our paging algorithm, so there goes my previous theory...

**Comment by dcolligan** [comment] 2015-06-16 02:46
@jeromekelleher is there a way of deriving a unique id from a `GAVariant`?  There are duplicate `variant.id`s within the result set, and also duplicate `(referenceName, start, end)`s within the set.  Computing a sha over the `variant.toJsonString()` doesn't work since the fields within the JSON string aren't predictably ordered.  I suppose as a last resort I could create a method that converted all the variant's attributes to a string in a predictable way, then hash it, but is there something easier?  It's hard to determine what is going wrong with the paging if I can't easily tell one variant from another...

**Comment by jeromekelleher** [comment] 2015-06-16 14:53
This is tricky all right, and I can't see exactly what the problem is. I think our test coverage is a bit thin for the interval paging functionality (which is really quite complicated), so I've started an extra module to test the general code using randomly generated intervals. I'll keep going at this until it uncovers the same issue as we have here, and report back once there's some to update on. 

Sorry for the delay in fixing this @jingchunzhu.

**Comment by jeromekelleher** [comment] 2015-06-16 16:43
OK, starting to see the light here. This is definitely a fault in our interval paging algorithm. We're not handling the case where intervals in which the start coordinate is less than the query coordinate overlap with the search interval correctly. Working on a fix.

**Comment by jeromekelleher** [comment] 2015-06-17 14:33
This has been addressed in #457, and we'll try to make a bugfix release containing this and a few other bits and pieces ASAP. Thanks again for the report @jingchunzhu.

**Comment by dcolligan** [comment] 2015-06-24 16:05
Fixed in https://github.com/ga4gh/server/releases/tag/v0.1.2

**Closed by dcolligan** 2015-06-24 16:05 UTC
Labels: bug
