### ISSUE TITLE
A setup function was called after the first request was handled.  

### ISSUE THREAD

**Issue by bwalsh** [ga4gh/server#791] opened 2015-11-20 00:50 UTC
All:

Quick question,  I'm attempting to run full unit test suite and started to run into the following.
I've made no changes to test setup or front end...   does this look familiar to anyone?

Thanks,

-b

**Comment by jeromekelleher** [comment] 2015-11-20 08:02
It's not ringing any bells with me. Which tests are causing this? It would help to see the output verbatim without the markup --- can you put in some ``` around the quote please?

**Comment by bwalsh** [comment] 2015-11-20 15:16
Markup free out below

```
======================================================================
ERROR: test suite for <class 'tests.unit.test_oidc.TestFrontendOidc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/server/tests/unit/test_oidc.py", line 115, in setUpClass
    baseConfig="TestOidcConfig", extraConfig=config, port=8001)
  File "/server/ga4gh/frontend.py", line 172, in configure
    cors.CORS(app, allow_headers='Content-Type')
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 59, in __init__
    self.init_app(app, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 103, in init_app
    app.after_request(cors_after_request)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 55, in wrapper_func
    raise AssertionError('A setup function was called after the '
AssertionError: A setup function was called after the first request was handled.  This usually indicates a bug in the application where a module was not imported and decorators or other functionality was called too late.
To fix this make sure to import all your view modules, database models and everything related at a central place before the application starts serving requests.

======================================================================
ERROR: test suite for <class 'tests.unit.test_protocol_errors.TestFrontendErrors'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/server/tests/unit/test_protocol_errors.py", line 25, in setUpClass
    frontend.configure(baseConfig="TestConfig")
  File "/server/ga4gh/frontend.py", line 172, in configure
    cors.CORS(app, allow_headers='Content-Type')
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 59, in __init__
    self.init_app(app, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 103, in init_app
    app.after_request(cors_after_request)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 55, in wrapper_func
    raise AssertionError('A setup function was called after the '
AssertionError: A setup function was called after the first request was handled.  This usually indicates a bug in the application where a module was not imported and decorators or other functionality was called too late.
To fix this make sure to import all your view modules, database models and everything related at a central place before the application starts serving requests.

======================================================================
ERROR: test suite for <class 'tests.unit.test_simulated_stack.TestSimulatedStack'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/server/tests/unit/test_simulated_stack.py", line 43, in setUpClass
    baseConfig="TestConfig", extraConfig=config)
  File "/server/ga4gh/frontend.py", line 172, in configure
    cors.CORS(app, allow_headers='Content-Type')
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 59, in __init__
    self.init_app(app, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 103, in init_app
    app.after_request(cors_after_request)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 55, in wrapper_func
    raise AssertionError('A setup function was called after the '
AssertionError: A setup function was called after the first request was handled.  This usually indicates a bug in the application where a module was not imported and decorators or other functionality was called too late.
To fix this make sure to import all your view modules, database models and everything related at a central place before the application starts serving requests.

======================================================================
ERROR: test suite for <class 'tests.unit.test_views.TestFrontend'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/server/tests/unit/test_views.py", line 34, in setUpClass
    baseConfig="TestConfig", extraConfig=config)
  File "/server/ga4gh/frontend.py", line 172, in configure
    cors.CORS(app, allow_headers='Content-Type')
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 59, in __init__
    self.init_app(app, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 103, in init_app
    app.after_request(cors_after_request)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 55, in wrapper_func
    raise AssertionError('A setup function was called after the '
AssertionError: A setup function was called after the first request was handled.  This usually indicates a bug in the application where a module was not imported and decorators or other functionality was called too late.
To fix this make sure to import all your view modules, database models and everything related at a central place before the application starts serving requests.

Name                                 Stmts   Miss Branch BrMiss  Cover   Missing
--------------------------------------------------------------------------------
ga4gh                                    1      0      0      0   100%
ga4gh._protocol_definitions            986      0      0      0   100%
ga4gh.avrotools                        302     30     92     15    89%   87, 190, 196, 227, 238-241, 260, 268-271, 298, 301, 303, 347, 353, 371, 386, 414, 423, 438, 454, 468, 477, 486, 489, 492, 511-514
ga4gh.backend                          410     48    112     27    86%   46-47, 50-52, 353, 364, 409, 415, 436-440, 451-452, 454-455, 457-458, 473-474, 476-477, 498, 529-541, 574-575, 581, 606-607, 612-613, 629-633, 760
ga4gh.cli                              584    172    112     80    64%   43-61, 65-77, 93, 181-184, 190-194, 212, 262-263, 273-274, 277-278, 281-285, 293-295, 298-300, 303-307, 315-317, 320-322, 325-329, 340-353, 361-371, 374-378, 381-385, 399, 427-428, 434-436, 444-456, 459-462, 468-470, 491, 509-510, 518-519, 527-528, 536-537, 545-546, 563-564, 964, 967, 971-974, 986-990, 993-1002, 1035-1041, 1054-1059, 1062-1066, 1094-1100, 1115, 1119, 1124-1160
ga4gh.client                           194      7     14      3    95%   33, 44, 70, 99, 124, 451-452
ga4gh.configtest                        24     12      4      4    43%   34-44, 51-54
ga4gh.converters                       148     25     53     15    80%   23-26, 61, 117, 183, 186, 189, 192, 212, 215-218, 246-254, 257-261, 269-270
ga4gh.datamodel                        207      3     60      1    99%   69, 85-86
ga4gh.datamodel.datasets               103      4     20      5    93%   102-104, 118
ga4gh.datamodel.genotype_phenotype     158      4     65      4    96%   64, 147, 362, 366
ga4gh.datamodel.reads                  405     19     68      6    95%   151, 157, 163, 190, 220, 225, 354, 360, 366, 372, 378, 384, 390, 396, 402, 408, 414, 420, 551
ga4gh.datamodel.references             215      4     22      0    98%   289, 418-419, 425
ga4gh.datamodel.variants               291     14     85      7    94%   46, 62-70, 231, 341, 467, 481
ga4gh.exceptions                       196      1      8      1    99%   269
ga4gh.frontend                         260    114     58     41    51%   59-61, 83-87, 93, 99, 105, 111, 118-119, 125, 131, 137, 143, 164, 166, 197-200, 213-251, 267, 276-277, 285-286, 293-295, 319-332, 353-360, 368-371, 379-382, 392-395, 424-425, 431, 436, 442, 448, 454, 460, 466, 472, 478, 484, 490, 496, 510, 518, 526, 532, 540, 559-601, 608, 617, 622, 627
ga4gh.protocol                         108      1     44      2    98%   196
ga4gh.serverconfig                      67      0      0      0   100%
ga4gh.templates                          0      0      0      0   100%
--------------------------------------------------------------------------------
TOTAL                                 4659    458    817    211    88%
----------------------------------------------------------------------
Ran 407 tests in 52.565s

FAILED (SKIP=1, errors=4)
*** ERROR
```

Also, the tests work fine when run individually

```
root@951b2bb0413f:/server# nosetests tests.unit.test_simulated_stack.TestSimulatedStack

----------------------------------------------------------------------
Ran 0 tests in 0.031s

OK
root@951b2bb0413f:/server#
root@951b2bb0413f:/server# nosetests tests.unit.test_views.TestFrontend

----------------------------------------------------------------------
Ran 0 tests in 0.023s

OK
root@951b2bb0413f:/server# nosetests tests.unit.test_oidc.TestFrontendOidc

----------------------------------------------------------------------
Ran 0 tests in 40.078s

OK
```

**Comment by dcolligan** [comment] 2015-11-20 17:28
Haven't seen that one before...

**Comment by bwalsh** [comment] 2015-11-20 22:47
Found it.

In ga4gh/serverconfig.py
```
class FlaskDefaultConfig(object):
    """
    The default values for the Flask config.
    Only used in testing.
    """
    APPLICATION_ROOT = None
    DEBUG = False                     <------------ if this is false it causes this problem

```

**Comment by jeromekelleher** [comment] 2015-11-23 21:13
Eesh. Good ole Flask, eh?

If this has been resolved, can we close the issue @bwalsh?

**Comment by bwalsh** [comment] 2015-11-23 21:15
Sure, go ahead and close. thanks

-Brian Walsh

**Closed** 2015-11-23 21:19 UTC

**Comment by chaosagent** [comment] 2016-02-17 02:02
I just ran into this problem a few minutes ago too. Does anyone have any guesses as to what the cause of this problem is?
I have two tests. If I comment out the setup to the test that fails, all tests pass, despite not having the router set up. Both tests are for very simple @blueprint('/') def thing: return 'hi' like methods.

**Comment by jeromekelleher** [comment] 2016-02-17 16:37
Is there any chance that there are some old servers running? Sometimes this mucks things up.  Try
```
ps aux | grep python
```
If you see some old server-like processes running try killing them. Otherwise, can you give us a bit more detail (i.e., some backtraces)?

**Comment by bwalsh** [comment] 2016-02-17 16:53
The only time I've seen this is because of `DEBUG = True` in the setup (see above).
I just verified that that behavior still exists. Now why exactly it exists, or other triggers for the behavior, I'm not sure.
